[package]
name = "more_math"
version = "1.2.1"
license = "MIT"
authors = ["Chao Xu <fardream@users.noreply.github.com>"]

[dependencies]

[dev-dependencies]
MoveStdlib = { git = "git@github.com:move-language/move.git", rev = "main", subdir = "language/move-stdlib" }
MoveNursery = { git = "git@github.com:move-language/move.git", rev = "main", subdir = "language/move-stdlib/nursery" }

[addresses]
more_math = "0x0"

[dev-addresses]
std = "0x1"