[package]
name = "more_math"
version = "0.0.0"

[dependencies]
MoveStdlib = { git = "git@github.com:move-language/move.git", rev = "main", subdir = "language/move-stdlib" }
MoveNursery = { git = "git@github.com:move-language/move.git", rev = "main", subdir = "language/move-stdlib/nursery" }

[addresses]
std = "0x1"
more_math = "0x0"
